"use client"

import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'es' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string | string[]
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  es: {
    // Header
    'header.rental': 'Alquiler',
    'header.tours': 'Visitas Guiadas',
    'header.shop': 'Tienda',
    'header.contact': 'Contacto',
    'header.scanPrices': 'Rent a Quad',
    
    // Hero Section
    'hero.title': 'Explora con Libertad',
    'hero.subtitle': 'Alquila bicicletas, patinetes eléctricos, motos, coches y únete a nuestras visitas guiadas. La aventura te espera en cada rincón.',
    'hero.viewRentals': 'Ver Alquileres',
    'hero.bookTour': 'Reservar Tour',
    
    // Services Section
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Descubre todas las opciones que tenemos para hacer tu experiencia inolvidable',
    'services.bikeRental': 'Alquiler de Bicicletas',
    'services.bikeDescription': 'Bicicletas eléctricas, mountain bikes, city bikes y más',
    'services.guidedTours': 'Visitas Guiadas',
    'services.toursDescription': 'Tours y excursiones por los mejores lugares',
    'services.carRental': 'Alquiler de Coches',
    'services.carDescription': 'Desde compactos hasta minibuses de 9 plazas',
    'services.motosScooters': 'Motos y Scooters',
    'services.motosDescription': 'Motos, patinetes - scooters eléctricos y quads',
    
    // Location Section
    'location.title': 'Donde Estamos',
    'location.subtitle': 'Nos encontramos en el corazón de Torremolinos, listos para tu próxima aventura',
    'location.description': 'Visítanos en nuestra ubicación privilegiada a orillas del mar mediterráneo en Torremolinos donde podrás encontrar todo lo que necesitas para tu aventura.',
    'location.ourLocation': 'Nuestra Ubicación',
    'location.address': 'Calle de la Playa, 22',
    'location.city': '29620 Torremolinos, Málaga',
    'location.country': 'España',
    'location.phone': '+34 655 707 412',
    'location.email': 'rentairstreet@gmail.com',
    'location.hours': 'Lunes a Domingo: 9:00 - 20:00',
    'location.streetView': 'Ver en Street View',
    
    // Prices Section
    'prices.title': 'Precios Destacados',
    'prices.subtitle': 'Algunas de nuestras ofertas más populares',
    'prices.cityBike': 'Bici City',
    'prices.cityBikeDesc': 'Perfecta para paseos urbanos',
    'prices.electricBike': 'Bici Eléctrica',
    'prices.electricBikeDesc': 'Sin esfuerzo, máxima diversión',
    'prices.traditionalScooter': 'Patinete Tradicional',
    'prices.traditionalScooterDesc': 'Ligero y divertido para distancias cortas',
    'prices.hour': '1 hora',
    'prices.allDay': 'Todo el día (11h)',
    'prices.halfHour': '30 min',
    
    // Featured Tours
    'tours.title': 'Tours Destacados',
    'tours.subtitle': 'Descubre nuestras experiencias más populares y vive aventuras inolvidables',
    'tours.dolphinTrip': 'Dolphin Trip',
    'tours.dolphinDesc': 'Avistamiento de delfines en su hábitat natural. Perfecto para familias.',
    'tours.granadaAlhambra': 'Granada Alhambra',
    'tours.granadaDesc': 'Visita la majestuosa Alhambra y los jardines del Generalife.',
    'tours.horseRiding': 'Paseos a Caballo',
    'tours.horseDesc': 'Disfruta de un relajante paseo a caballo por paisajes naturales únicos.',
    'tours.adults': 'Adultos',
    'tours.children': 'Niños: 12€',
    'tours.familyExperience': 'Experiencia familiar',
    'tours.thursdayFriday': 'Jueves y Viernes',
    'tours.unescoHeritage': 'Patrimonio UNESCO',
    'tours.officialGuide': 'Guía oficial incluido',
    'tours.duration': '1.30 horas',
    'tours.onePersonPerHorse': '1 persona por caballo',
    'tours.expertGuide': 'Guía experto incluido',
    'tours.viewAllTours': 'Ver Todos los Tours',
    
    // Contact Section
    'contact.title': 'Contacto',
    
    // Footer
    'footer.rights': '© 2025 Free Air Street. Todos los derechos reservados.',
    
    // Rental Page
    'rental.title': 'Alquiler de Vehículos',
    'rental.subtitle': 'Descubre la libertad de moverte por Torremolinos con nuestras bicicletas, coches, motos, patinetes eléctricos y quads. ¡Elige tu vehículo ideal y vive una experiencia única!',
    'rental.bicycles': 'Bicicletas',
    'rental.cars': 'Coches',
    'rental.motorcycles': 'Motos',
    'rental.quads': 'Quads',
    'rental.scooters': 'Scooters',
    'rental.accessories': 'Accesorios',
    'rental.selectPrice': 'Seleccionar Precio',
    'rental.reserve': 'Reservar',
    'rental.allDay': 'Todo el día (11h)',
    'rental.day': 'Día',
    'rental.days': 'días',
    'rental.hour': 'hora',
    'rental.hours': 'horas',
    'rental.min': 'min',
    'rental.consultPrice': 'Consultar precio',
    'rental.consultAvailability': 'Consultar disponibilidad',
    'rental.features': 'Características:',
    'rental.prices': 'Precios:',
    'rental.for': 'por',
    'rental.carRequirements.title': 'Requisitos para alquiler de coches:',
    'rental.carRequirements.license': 'Carnet de conducir en vigor',
    'rental.carRequirements.passport': 'Pasaporte o DNI',
    'rental.carRequirements.creditCard': 'Tarjeta de crédito para fianza',
    'rental.carRequirements.age': 'Edad mínima: 21 años',
    'rental.carRequirements.models': 'Los modelos pueden variar según disponibilidad',
    // Vehicle translations
    'rental.vehicles.cityBike.name': 'City Bike',
    'rental.vehicles.cityBike.description': 'Perfecta para paseos urbanos y desplazamientos por la ciudad',
    'rental.vehicles.cityBike.allDay': 'Todo el día',
    'rental.vehicles.cityBike.features': ['Cesta delantera', 'Luces LED', 'Cambio de 7 velocidades', 'Asiento cómodo'],
    'rental.vehicles.mountainBike.name': 'MOUNTAIN BIKE / BICI CARRETERA',
    'rental.vehicles.mountainBike.description': 'Ideal para aventuras en montaña y carretera',
    'rental.vehicles.mountainBike.allDay': 'Todo el día (11h)',
    'rental.vehicles.mountainBike.features': ['Suspensión delantera', 'Frenos de disco', '21 velocidades', 'Neumáticos todo terreno'],
    'rental.vehicles.electricBike.name': 'BIKE ELECT (Bicicleta eléctrica)',
    'rental.vehicles.electricBike.description': 'Pedaleo asistido para recorridos sin esfuerzo',
    'rental.vehicles.electricBike.allDay': 'Todo el día (11h)',
    'rental.vehicles.electricBike.features': ['Motor eléctrico', 'Batería de larga duración', 'Pantalla LCD', 'Cargador incluido'],
    'rental.vehicles.fatBike.name': 'FAT BIKE ELECTRIC',
    'rental.vehicles.fatBike.description': 'Bicicleta eléctrica con neumáticos anchos para cualquier terreno',
    'rental.vehicles.fatBike.allDay': 'Todo el día (11h)',
    'rental.vehicles.fatBike.features': ['Neumáticos anchos', 'Motor potente', 'Suspensión completa', 'Resistente al agua'],
    'rental.vehicles.toyotaAygo.group': 'Grupo A',
    'rental.vehicles.toyotaAygo.description': 'Compacto y económico, perfecto para la ciudad',
    'rental.vehicles.toyotaAygo.duration1': '1 Día',
    'rental.vehicles.toyotaAygo.features': ['Aire acondicionado', 'Dirección asistida', '5 puertas', 'Consumo eficiente'],

    // Tours Page
    'tours.pageTitle': 'Visitas Guiadas y Excursiones',
    'tours.pageSubtitle': 'Descubre los lugares más increíbles de Andalucía con nuestras excursiones organizadas y actividades únicas',
    'tours.excursions': 'Excursiones',
    'tours.activities': 'Actividades',
    'tours.boatActivities': 'Actividades en Barco',
    'tours.price': 'Precio',
    'tours.from': 'Desde',
    'tours.adult': 'Adulto',
    'tours.child': 'Niño',
    'tours.person': 'persona',
    'tours.capacity': 'Capacidad',
    'tours.location': 'Ubicación',
    'tours.highlights': 'Destacados',
    'tours.languages': 'Idiomas disponibles',
    'tours.spanish': 'Español',
    'tours.english': 'Inglés',
    'tours.french': 'Francés',
    'tours.german': 'Alemán',
    'tours.italian': 'Italiano',
    'tours.importantInfo': 'Información Importante',
    'tours.whatIncludes': '¿Qué incluye?',
    'tours.recommendations': 'Recomendaciones',
    'tours.includes1': 'Transporte en autocar climatizado',
    'tours.includes2': 'Guía oficial en español',
    'tours.includes3': 'Seguro de viaje incluido',
    'tours.includes4': 'Tiempo libre para explorar',
    'tours.rec1': 'Llevar calzado cómodo',
    'tours.rec2': 'Protección solar recomendada',
    'tours.rec3': 'Cámara para capturar momentos',
    'tours.rec4': 'Documentación en regla',
    
    // Contact Page
    'contact.subtitle': '¿Tienes alguna pregunta o necesitas más información? Estamos aquí para ayudarte. Contáctanos y te responderemos lo antes posible.',
    'contact.phone': 'Teléfono',
    'contact.phoneHours': 'Disponible de 9:00 a 20:00',
    'contact.email': 'Email',
    'contact.emailResponse': 'Respuesta en 24h',
    'contact.location': 'Ubicación',
    'contact.hours': 'Horarios',
    'contact.schedule': 'Lun - Dom: 9:00 - 20:00',
    'contact.openDaily': 'Abierto todos los días',
    'contact.mondayToSunday': 'Lunes - Domingo',
    'contact.regularHours': '9:00 - 20:00',
    'contact.holidays': 'Festivos',
    'contact.holidayHours': '10:00 - 19:00',
    'contact.form.title': 'Envíanos un mensaje',
    'contact.form.description': 'Completa el formulario y nos pondremos en contacto contigo lo antes posible.',
    'contact.form.name': 'Nombre',
    'contact.form.namePlaceholder': 'Tu nombre completo',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'tu@email.com',
    'contact.form.phone': 'Teléfono',
    'contact.form.phonePlaceholder': '+34 XXX XXX XXX',
    'contact.form.subject': 'Asunto',
    'contact.form.subjectPlaceholder': '¿En qué podemos ayudarte?',
    'contact.form.message': 'Mensaje',
    'contact.form.messagePlaceholder': 'Cuéntanos más detalles sobre tu consulta...',
    'contact.form.send': 'Enviar mensaje',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': '¡Mensaje enviado!',
    'contact.form.successMessage': 'Te responderemos lo antes posible.',
    'contact.form.sendAnother': 'Enviar otro mensaje',
    'contact.form.error': 'Error al enviar el mensaje',
    'contact.form.errorMessage': 'Por favor, inténtalo de nuevo o contáctanos directamente.',
    'contact.info.title': 'Información de Contacto',
    'contact.info.phone': 'Teléfono',
    'contact.info.phoneDesc': 'Llámanos de 9:00 a 20:00',
    'contact.info.email': 'Email',
    'contact.info.emailDesc': 'Respuesta en 24h',
    'contact.info.location': 'Ubicación',
    'contact.info.address': 'Calle de la Playa, 22',
    'contact.info.city': '29620 - Torremolinos',
    'contact.hours.title': 'Horarios de Atención',
    'contact.hours.weekdays': 'Lunes - Domingo',
    'contact.hours.weekdaysTime': '9:00 - 20:00',
    'contact.hours.holidays': 'Festivos',
    'contact.hours.holidaysTime': '10:00 - 19:00',
    'contact.map.title': 'Nuestra Ubicación',
    'contact.callNow': 'Llamar Ahora',
  },
  en: {
    // Header
    'header.rental': 'Rental',
    'header.tours': 'Guided Tours',
    'header.shop': 'Shop',
    'header.contact': 'Contact',
    'header.scanPrices': 'Rent a Quad',
    
    // Hero Section
    'hero.title': 'Explore with Freedom',
    'hero.subtitle': 'Rent bikes, electric scooters, motorcycles, cars and join our guided tours. Adventure awaits you at every corner.',
    'hero.viewRentals': 'View Rentals',
    'hero.bookTour': 'Book Tour',
    
    // Services Section
    'services.title': 'Our Services',
    'services.subtitle': 'Discover all the options we have to make your experience unforgettable',
    'services.bikeRental': 'Bike Rental',
    'services.bikeDescription': 'Electric bikes, mountain bikes, city bikes and more',
    'services.guidedTours': 'Guided Tours',
    'services.toursDescription': 'Tours and excursions to the best places',
    'services.carRental': 'Car Rental',
    'services.carDescription': 'From compact cars to 9-seater minibuses',
    'services.motosScooters': 'Motorcycles & Scooters',
    'services.motosDescription': 'Motorcycles, electric scooters and quads',
    
    // Location Section
    'location.title': 'Where We Are',
    'location.subtitle': 'We are located in the heart of Torremolinos, ready for your next adventure',
    'location.description': 'Visit us at our privileged location on the shores of the Mediterranean Sea in Torremolinos where you can find everything you need for your adventure.',
    'location.ourLocation': 'Our Location',
    'location.address': 'Calle de la Playa, 22',
    'location.city': '29620 Torremolinos, Málaga',
    'location.country': 'Spain',
    'location.phone': '+34 655 707 412',
    'location.email': 'rentairstreet@gmail.com',
    'location.hours': 'Monday to Sunday: 9:00 - 20:00',
    'location.streetView': 'View in Street View',
    
    // Prices Section
    'prices.title': 'Featured Prices',
    'prices.subtitle': 'Some of our most popular offers',
    'prices.cityBike': 'City Bike',
    'prices.cityBikeDesc': 'Perfect for urban rides',
    'prices.electricBike': 'Electric Bike',
    'prices.electricBikeDesc': 'No effort, maximum fun',
    'prices.traditionalScooter': 'Traditional Scooter',
    'prices.traditionalScooterDesc': 'Light and fun for short distances',
    'prices.hour': '1 hour',
    'prices.allDay': 'All day (11h)',
    'prices.halfHour': '30 min',
    
    // Featured Tours
    'tours.title': 'Featured Tours',
    'tours.subtitle': 'Discover our most popular experiences and live unforgettable adventures',
    'tours.dolphinTrip': 'Dolphin Trip',
    'tours.dolphinDesc': 'Dolphin watching in their natural habitat. Perfect for families.',
    'tours.granadaAlhambra': 'Granada Alhambra',
    'tours.granadaDesc': 'Visit the majestic Alhambra and the Generalife gardens.',
    'tours.horseRiding': 'Horse Riding',
    'tours.horseDesc': 'Enjoy a relaxing horse ride through unique natural landscapes.',
    'tours.adults': 'Adults',
    'tours.children': 'Children: 12€',
    'tours.familyExperience': 'Family experience',
    'tours.thursdayFriday': 'Thursday and Friday',
    'tours.unescoHeritage': 'UNESCO Heritage',
    'tours.officialGuide': 'Official guide included',
    'tours.duration': '1.30 hours',
    'tours.onePersonPerHorse': '1 person per horse',
    'tours.expertGuide': 'Expert guide included',
    'tours.viewAllTours': 'View All Tours',
    
    // Contact Section
    'contact.title': 'Contact',
    
    // Footer
    'footer.rights': '© 2025 Free Air Street. All rights reserved.',
    
    // Rental Page
    'rental.title': 'Vehicle Rental',
    'rental.subtitle': 'Discover the freedom to move around Torremolinos with our bikes, cars, motorcycles, electric scooters and quads. Choose your ideal vehicle and live a unique experience!',
    'rental.bicycles': 'Bicycles',
    'rental.cars': 'Cars',
    'rental.motorcycles': 'Motorcycles',
    'rental.quads': 'Quads',
    'rental.scooters': 'Scooters',
    'rental.accessories': 'Accessories',
    'rental.selectPrice': 'Select Price',
    'rental.reserve': 'Reserve',
    'rental.allDay': 'All day (11h)',
    'rental.day': 'Day',
    'rental.days': 'days',
    'rental.hour': 'hour',
    'rental.hours': 'hours',
    'rental.min': 'min',
    'rental.consultPrice': 'Consult price',
    'rental.consultAvailability': 'Check availability',
    'rental.features': 'Features:',
    'rental.prices': 'Prices:',
    'rental.for': 'for',
    'rental.carRequirements.title': 'Car rental requirements:',
    'rental.carRequirements.license': 'Valid driving license',
    'rental.carRequirements.passport': 'Passport or ID',
    'rental.carRequirements.creditCard': 'Credit card for deposit',
    'rental.carRequirements.age': 'Minimum age: 21 years',
    'rental.carRequirements.models': 'Models may vary according to availability',
    // Vehicle translations
    'rental.vehicles.cityBike.name': 'City Bike',
    'rental.vehicles.cityBike.description': 'Perfect for urban rides and city commuting',
    'rental.vehicles.cityBike.allDay': 'All day',
    'rental.vehicles.cityBike.features': ['Front basket', 'LED lights', '7-speed gear', 'Comfortable seat'],
    'rental.vehicles.mountainBike.name': 'MOUNTAIN BIKE / ROAD BIKE',
    'rental.vehicles.mountainBike.description': 'Ideal for mountain and road adventures',
    'rental.vehicles.mountainBike.allDay': 'All day (11h)',
    'rental.vehicles.mountainBike.features': ['Front suspension', 'Disc brakes', '21 speeds', 'All-terrain tires'],
    'rental.vehicles.electricBike.name': 'ELECTRIC BIKE',
    'rental.vehicles.electricBike.description': 'Pedal assist for effortless rides',
    'rental.vehicles.electricBike.allDay': 'All day (11h)',
    'rental.vehicles.electricBike.features': ['Electric motor', 'Long-lasting battery', 'LCD display', 'Charger included'],
    'rental.vehicles.fatBike.name': 'FAT BIKE ELECTRIC',
    'rental.vehicles.fatBike.description': 'Electric bike with wide tires for any terrain',
    'rental.vehicles.fatBike.allDay': 'All day (11h)',
    'rental.vehicles.fatBike.features': ['Wide tires', 'Powerful motor', 'Full suspension', 'Water resistant'],
    'rental.vehicles.toyotaAygo.group': 'Group A',
    'rental.vehicles.toyotaAygo.description': 'Compact and economical, perfect for the city',
    'rental.vehicles.toyotaAygo.duration1': '1 Day',
    'rental.vehicles.toyotaAygo.features': ['Air conditioning', 'Power steering', '5 doors', 'Efficient consumption'],
    
    // Tours Page
    'tours.pageTitle': 'Guided Tours and Excursions',
    'tours.pageSubtitle': 'Discover the most incredible places in Andalusia with our organized excursions and unique activities',
    'tours.excursions': 'Excursions',
    'tours.activities': 'Activities',
    'tours.boatActivities': 'Boat Activities',
    'tours.price': 'Price',
    'tours.from': 'From',
    'tours.adult': 'Adult',
    'tours.child': 'Child',
    'tours.person': 'person',
    'tours.capacity': 'Capacity',
    'tours.location': 'Location',
    'tours.highlights': 'Highlights',
    'tours.languages': 'Available languages',
    'tours.spanish': 'Spanish',
    'tours.english': 'English',
    'tours.french': 'French',
    'tours.german': 'German',
    'tours.italian': 'Italian',
    'tours.importantInfo': 'Important Information',
    'tours.whatIncludes': 'What includes?',
    'tours.recommendations': 'Recommendations',
    'tours.includes1': 'Air-conditioned bus transport',
    'tours.includes2': 'Official guide in Spanish',
    'tours.includes3': 'Travel insurance included',
    'tours.includes4': 'Free time to explore',
    'tours.rec1': 'Wear comfortable shoes',
    'tours.rec2': 'Sun protection recommended',
    'tours.rec3': 'Camera to capture moments',
    'tours.rec4': 'Documentation in order',
    
    // Contact Page
    'contact.subtitle': 'Do you have any questions or need more information? We are here to help you. Contact us and we will respond as soon as possible.',
    'contact.phone': 'Phone',
    'contact.phoneHours': 'Available from 9:00 to 20:00',
    'contact.email': 'Email',
    'contact.emailResponse': '24h response',
    'contact.location': 'Location',
    'contact.hours': 'Hours',
    'contact.schedule': 'Mon - Sun: 9:00 - 20:00',
    'contact.openDaily': 'Open every day',
    'contact.mondayToSunday': 'Monday - Sunday',
    'contact.regularHours': '9:00 - 20:00',
    'contact.holidays': 'Holidays',
    'contact.holidayHours': '10:00 - 19:00',
    'contact.form.title': 'Send us a message',
    'contact.form.description': 'Fill out the form and we will get in touch with you as soon as possible.',
    'contact.form.name': 'Name',
    'contact.form.namePlaceholder': 'Your full name',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.phone': 'Phone',
    'contact.form.phonePlaceholder': '+34 XXX XXX XXX',
    'contact.form.subject': 'Subject',
    'contact.form.subjectPlaceholder': 'How can we help you?',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Tell us more details about your inquiry...',
    'contact.form.send': 'Send message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent!',
    'contact.form.successMessage': 'We will respond as soon as possible.',
    'contact.form.sendAnother': 'Send another message',
    'contact.form.error': 'Error sending message',
    'contact.form.errorMessage': 'Please try again or contact us directly.',
    'contact.info.title': 'Contact Information',
    'contact.info.phone': 'Phone',
    'contact.info.phoneDesc': 'Call us from 9:00 to 20:00',
    'contact.info.email': 'Email',
    'contact.info.emailDesc': '24h response',
    'contact.info.location': 'Location',
    'contact.info.address': 'Calle de la Playa, 22',
    'contact.info.city': '29620 - Torremolinos',
    'contact.hours.title': 'Business Hours',
    'contact.hours.weekdays': 'Monday - Sunday',
    'contact.hours.weekdaysTime': '9:00 - 20:00',
    'contact.hours.holidays': 'Holidays',
    'contact.hours.holidaysTime': '10:00 - 19:00',
    'contact.map.title': 'Our Location',
    'contact.callNow': 'Call Now',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es')

  const t = (key: string): string | string[] => {
    return translations[language][key as keyof typeof translations['es']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}