"use client"

import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'es' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string | string[]
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  es: {
    // Header
    'header.rental': 'Alquiler',
    'header.tours': 'Visitas Guiadas',
    'header.shop': 'Tienda',
    'header.contact': 'Contacto',
    'header.scanPrices': 'Rent a Quad',
    
    // Hero Section
    'hero.title': 'Explora con Libertad',
    'hero.subtitle': 'Alquila bicicletas, patinetes eléctricos, motos, coches y únete a nuestras visitas guiadas. La aventura te espera en cada rincón.',
    'hero.viewRentals': 'Ver Alquileres',
    'hero.bookTour': 'Reservar Tour',
    
    // Services Section
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Descubre todas las opciones que tenemos para hacer tu experiencia inolvidable',
    'services.bikeRental': 'Alquiler de Bicicletas',
    'services.bikeDescription': 'Bicicletas eléctricas, mountain bikes, city bikes y más',
    'services.guidedTours': 'Visitas Guiadas',
    'services.toursDescription': 'Tours y excursiones por los mejores lugares',
    'services.carRental': 'Alquiler de Coches',
    'services.carDescription': 'Desde compactos hasta minibuses de 9 plazas',
    'services.motosScooters': 'Motos y Scooters',
    'services.motosDescription': 'Motos, patinetes - scooters eléctricos y quads',
    'services.repairService': 'Servicio de reparación',
    'services.repairDescription': 'Reparación y mantenimiento',
    'services.store': 'Tienda',
    'services.storeDescription': 'Descubre nuestra selección de productos y accesorios',
    // Common
    'common.seeMore': 'Ver más →',
    
    // Location Section
    'location.title': 'Donde Estamos',
    'location.description.before': 'Visítanos en nuestra ubicación privilegiada a orillas del Mar de Alborán en La Colina ',
    'location.description.after': ' donde podrás encontrar todo lo que necesitas para tu aventura.',
    'location.subtitle': 'Nos encontramos en el corazón de Torremolinos, listos para tu próxima aventura',
    'location.description': 'Visítanos en nuestra ubicación privilegiada a orillas del mar mediterráneo en Torremolinos donde podrás encontrar todo lo que necesitas para tu aventura.',
    'location.ourLocation': 'Nuestra Ubicación',
    'location.address': 'Calle de la Playa, 22',
    'location.city': '29620 Torremolinos, Málaga, La Colina',
    'location.country': 'España',
    'location.phone': '+34 655 707 412',
    'location.email': 'rentairstreet@gmail.com',
    'location.hours': 'Lunes a Domingo: 9:00 - 22:00',
    'location.streetView': 'Ver en Street View',
    
    // Second Store Section
    'secondStore.title': 'Puedes dejar la bicicleta en nuestra',
    'secondStore.otherStore': 'otra tienda',
    'secondStore.available': 'disponible',
    'secondStore.secondLocation': 'Segunda ubicación',
    'secondStore.address': 'Calle Obispo Juan Alonso 8',
    'secondStore.city': 'Los Álamos, Torremolinos',
    'secondStore.description': 'Para tu comodidad, también puedes devolver tu bicicleta en nuestra segunda tienda. Perfecta para rutas que terminen en esa zona de Torremolinos.',
    'secondStore.viewOnMaps': 'Ver en Google Maps',
    
    // Prices Section
    'prices.title': 'Precios Destacados',
    'prices.subtitle': 'Algunas de nuestras ofertas más populares',
    'prices.cityBike': 'Bici City',
    'prices.cityBikeDesc': 'Perfecta para paseos urbanos',
    'prices.electricBike': 'Bici Eléctrica',
    'prices.electricBikeDesc': 'Sin esfuerzo, máxima diversión',
    'prices.traditionalScooter': 'Patinete Tradicional',
    'prices.traditionalScooterDesc': 'Ligero y divertido para distancias cortas',
    'prices.hour': '1 hora',
    'prices.allDay': 'Todo el día (11h)',
    'prices.halfHour': '30 min',
    
    // Featured Tours
    'tours.title': 'Tours Destacados',
    'tours.subtitle': 'Descubre nuestras experiencias más populares y vive aventuras inolvidables',
    'tours.dolphinTrip': 'Dolphin Trip',
    'tours.dolphinDesc': 'Avistamiento de delfines en su hábitat natural. Perfecto para familias.',
    'tours.granadaAlhambra': 'Granada Alhambra',
    'tours.granadaDesc': 'Visita la majestuosa Alhambra y los jardines del Generalife.',
    'tours.horseRiding': 'Paseos a Caballo',
    'tours.horseDesc': 'Disfruta de un relajante paseo a caballo por paisajes naturales únicos.',
    'tours.adults': 'Adultos',
    'tours.children': 'Niños',
    'tours.familyExperience': 'Experiencia familiar',
    'tours.thursdayFriday': 'Jueves y Viernes',
    'tours.unescoHeritage': 'Patrimonio UNESCO',
    'tours.officialGuide': 'Guía oficial incluido',
    'tours.duration': '1.30 horas',
    'tours.onePersonPerHorse': '1 persona por caballo',
    'tours.expertGuide': 'Guía experto incluido',
    'tours.viewAllTours': 'Ver Todos los Tours',
    
    // Contact Section
    'contact.title': 'Contacto',
    
    // Footer
    'footer.rights': '© 2025 Free Air Street. Todos los derechos reservados.',
    
    // Rental Page
    'rental.title': 'Alquiler de Vehículos',
    'rental.subtitle': 'Descubre la libertad de moverte por Torremolinos con nuestras bicicletas, coches, motos, patinetes eléctricos y quads. ¡Elige tu vehículo ideal y vive una experiencia única!',
    'rental.bicycles': 'Bicicletas',
    'rental.cars': 'Coches',
    'rental.motorcycles': 'Motos',
    'rental.quads': 'Quads',
    'rental.scooters': 'Scooters',
    'rental.accessories': 'Accesorios',
    'rental.selectPrice': 'Seleccionar Precio',
    'rental.reserve': 'Reservar',
    'rental.allDay': 'Todo el día (11h)',
    'rental.day': 'Día',
    'rental.days': 'días',
    'rental.hour': 'hora',
    'rental.hours': 'horas',
    'rental.min': 'min',
    'rental.consultPrice': 'Consultar precio',
    'rental.consultAvailability': 'Consultar disponibilidad',
    'rental.features': 'Características:',
    'rental.prices': 'Precios:',
    'rental.for': 'por',
    'rental.model': 'Modelo:',
    'rental.autonomy': 'Autonomía',
    'rental.speed': 'Velocidad',
    'rental.carRequirements.title': 'Requisitos para alquiler de coches:',
    'rental.carRequirements.license': 'Carnet de conducir en vigor',
    'rental.carRequirements.passport': 'Pasaporte o DNI',
    'rental.carRequirements.creditCard': 'Tarjeta de crédito para fianza',
    'rental.carRequirements.age': 'Edad mínima: 21 años',
    'rental.carRequirements.models': 'Los modelos pueden variar según disponibilidad',
    // Motorcycle Requirements
    'rental.motorcycleRequirements.title': 'Requisitos para Alquiler de Motos',
    'rental.motorcycleRequirements.license': 'Carnet de conducir válido y vigente (A1, A2 o A según cilindrada)',
    'rental.motorcycleRequirements.reservation': 'Reserva obligatoria con antelación',
    'rental.motorcycleRequirements.id': 'Documento de identidad (DNI o pasaporte)',
    'rental.motorcycleRequirements.minAge': 'Edad mínima: 16 años (50cc), 18 años (125cc), 20 años (+300cc)',
    'rental.motorcycleRequirements.deposit': 'Depósito de seguridad requerido',
    'rental.motorcycleRequirements.helmet': 'Casco homologado incluido',
    // Quad Requirements
    'rental.quadRequirements.title': 'Requisitos para Alquiler de Quads',
    'rental.quadRequirements.license': 'Carnet de conducir válido y vigente (B o superior)',
    'rental.quadRequirements.reservation': 'Reserva obligatoria con antelación',
    'rental.quadRequirements.id': 'Documento de identidad (DNI o pasaporte)',
    'rental.quadRequirements.minAge': 'Edad mínima: 18 años',
    'rental.quadRequirements.deposit': 'Depósito de seguridad requerido',
    'rental.quadRequirements.helmet': 'Casco homologado incluido',
    'rental.quadRequirements.safetyBriefing': 'Briefing de seguridad obligatorio',
    // Vehicle translations
    'rental.vehicles.cityBike.name': 'City Bike',
    'rental.vehicles.cityBike.description': 'Perfecta para paseos urbanos y desplazamientos por la ciudad',
    'rental.vehicles.cityBike.allDay': 'Todo el día',
    'rental.vehicles.cityBike.features': ['Cesta delantera', 'Luces LED', 'Cambio de 7 velocidades', 'Asiento cómodo'],
    'rental.vehicles.mountainBike.name': 'MOUNTAIN BIKE / BICI CARRETERA',
    'rental.vehicles.mountainBike.description': 'Ideal para aventuras en montaña y carretera',
    'rental.vehicles.mountainBike.allDay': 'Todo el día (11h)',
    'rental.vehicles.mountainBike.features': ['Suspensión delantera', 'Frenos de disco', '21 velocidades', 'Neumáticos todo terreno'],
    'rental.vehicles.electricBike.name': 'BIKE ELECT (Bicicleta eléctrica)',
    'rental.vehicles.electricBike.description': 'Pedaleo asistido para recorridos sin esfuerzo',
    'rental.vehicles.electricBike.allDay': 'Todo el día (11h)',
    'rental.vehicles.electricBike.features': ['Motor eléctrico', 'Batería de larga duración', 'Pantalla LCD', 'Cargador incluido'],
    'rental.vehicles.fatBike.name': 'FAT BIKE ELECTRIC',
    'rental.vehicles.fatBike.description': 'Bicicleta eléctrica con neumáticos anchos para cualquier terreno',
    'rental.vehicles.fatBike.allDay': 'Todo el día (11h)',
    'rental.vehicles.fatBike.features': ['Neumáticos anchos', 'Motor potente', 'Suspensión completa', 'Resistente al agua'],
    'rental.vehicles.toyotaAygo.group': 'Grupo A',
    'rental.vehicles.toyotaAygo.description': 'Compacto y económico, perfecto para la ciudad',
    'rental.vehicles.toyotaAygo.duration1': '1 Día',
    'rental.vehicles.toyotaAygo.features': ['Aire acondicionado', 'Dirección asistida', '5 puertas', 'Consumo eficiente'],

    // Tours Page
    'tours.pageTitle': 'Visitas Guiadas y Excursiones',
    'tours.pageSubtitle': 'Descubre los lugares más increíbles de Andalucía con nuestras excursiones organizadas y actividades únicas',
    'tours.excursions': 'Excursiones',
    'tours.activities': 'Actividades',
    'tours.boatActivities': 'Actividades en Barco',
    'tours.availableDays': 'Días disponibles:',
    'tours.price': 'Precio',
    'tours.from': 'Desde',
    'tours.adult': 'Adulto',
    'tours.child': 'Niño',
    'tours.person': 'persona',
    'tours.capacity': 'Capacidad',
    'tours.location': 'Ubicación',
    'tours.highlights': 'Destacados',
    'tours.languages': 'Idiomas disponibles',
    'tours.spanish': 'Español',
    'tours.english': 'Inglés',
    'tours.french': 'Francés',
    'tours.german': 'Alemán',
    'tours.italian': 'Italiano',
    'tours.importantInfo': 'Información Importante',
    'tours.whatIncludes': 'Incluye:',
    'tours.recommendations': 'Recomendaciones',
    'tours.consult': 'Consultar',
    'tours.consultAvailability': 'Consultar disponibilidad',
    'tours.reserveActivity': 'Reservar Actividad',
    'tours.reserveRide': 'Reservar paseo',
    'tours.includes1': 'Transporte en autocar climatizado',
    'tours.includes2': 'Guía oficial en español',
    'tours.includes3': 'Seguro de viaje incluido',
    'tours.includes4': 'Tiempo libre para explorar',
    'tours.rec1': 'Llevar calzado cómodo',
    'tours.rec2': 'Protección solar recomendada',
    'tours.rec3': 'Cámara para capturar momentos',
    'tours.rec4': 'Documentación en regla',
    'tours.specialPrices.title': 'Precios Especiales',
    'tours.specialPrices.childrenFree': 'Niños (0-3 años): ¡GRATIS!',
    'tours.specialPrices.childrenDiscount': 'Niños (4-11 años): 25% de descuento',
    'tours.specialPrices.familyGroups': 'Grupos familiares: Consulta descuentos especiales',
    'tours.specialPrices.earlyBooking': 'Reserva anticipada: Mejores precios garantizados',
    'tours.languages.title': 'Idiomas Disponibles',
    'tours.languages.spanish': 'Español',
    'tours.languages.english': 'Inglés',
    'tours.languages.french': 'Francés',
    'tours.languages.german': 'Alemán',
    'tours.languages.italian': 'Italiano',
    'tours.importantInfo.title': 'Información Importante',
    'tours.importantInfo.includesTitle': '¿Qué incluye?',
    'tours.importantInfo.includes.transport': 'Transporte en autocar climatizado',
    'tours.importantInfo.includes.guide': 'Guía oficial certificado',
    'tours.importantInfo.includes.insurance': 'Seguro de viaje',
    'tours.importantInfo.includes.tickets': 'Entradas a monumentos (según tour)',
    'tours.importantInfo.includes.assistance': 'Asistencia durante todo el recorrido',
    'tours.importantInfo.recommendationsTitle': 'Recomendaciones',
    'tours.importantInfo.recommendations.shoes': 'Calzado cómodo para caminar',
    'tours.importantInfo.recommendations.sun': 'Protector solar y gorra',
    'tours.importantInfo.recommendations.camera': 'Cámara fotográfica',
    'tours.importantInfo.recommendations.docs': 'Documentación personal',
    'tours.importantInfo.recommendations.booking': 'Reserva con 48h de antelación',
    
    // Contact Page
    'contact.subtitle': '¿Tienes alguna pregunta o necesitas más información? Estamos aquí para ayudarte. Contáctanos y te responderemos lo antes posible.',
    'contact.phone': 'Teléfono',
    'contact.phoneHours': 'Disponible de 9:00 a 22:00',
    'contact.email': 'Email',
    'contact.emailResponse': 'Respuesta en 24h',
    'contact.location': 'Ubicación',
    'contact.hours': 'Horarios',
    'contact.schedule': 'Lun - Dom: 9:00 - 22:00',
    'contact.openDaily': 'Abierto todos los días',
    'contact.mondayToSunday': 'Lunes - Domingo',
    'contact.regularHours': '9:00 - 22:00',
    'contact.holidays': 'Festivos',
    'contact.holidayHours': '10:00 - 19:00',
    'contact.form.title': 'Envíanos un mensaje',
    'contact.form.description': 'Completa el formulario y nos pondremos en contacto contigo lo antes posible.',
    'contact.form.name': 'Nombre',
    'contact.form.namePlaceholder': 'Tu nombre completo',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'tu@email.com',
    'contact.form.phone': 'Teléfono',
    'contact.form.phonePlaceholder': '+34 XXX XXX XXX',
    'contact.form.subject': 'Asunto',
    'contact.form.subjectPlaceholder': '¿En qué podemos ayudarte?',
    'contact.form.message': 'Mensaje',
    'contact.form.messagePlaceholder': 'Cuéntanos más detalles sobre tu consulta...',
    'contact.form.send': 'Enviar mensaje',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': '¡Mensaje enviado!',
    'contact.form.successMessage': 'Te responderemos lo antes posible.',
    'contact.form.sendAnother': 'Enviar otro mensaje',
    'contact.form.error': 'Error al enviar el mensaje',
    'contact.form.errorMessage': 'Por favor, inténtalo de nuevo o contáctanos directamente.',
    'contact.info.title': 'Información de Contacto',
    'contact.info.phone': 'Teléfono',
    'contact.info.phoneDesc': 'Llámanos de 9:00 a 22:00',
    'contact.info.email': 'Email',
    'contact.info.emailDesc': 'Respuesta en 24h',
    'contact.info.location': 'Ubicación',
    'contact.info.address': 'Calle de la Playa, 22',
    'contact.info.city': '29620 - Torremolinos',
    'contact.hours.title': 'Horarios de Atención',
    'contact.hours.weekdays': 'Lunes - Domingo',
    'contact.hours.weekdaysTime': '9:00 - 22:00',
    'contact.hours.holidays': 'Festivos',
    'contact.hours.holidaysTime': '10:00 - 19:00',
    'contact.map.title': 'Nuestra Ubicación',
    'contact.callNow': 'Llamar Ahora',
    
    // Quad Tours
    'quadTours.title': 'EXPERIENCIA INOLVIDABLE',
    'quadTours.subtitle': 'TENEMOS 3 TOURS EN QUAD DISPONIBLES:',
    'quadTours.hour': 'HORA',
    'quadTours.tour': 'TOUR',
    'quadTours.price': 'PRECIO',
    'quadTours.single': 'SINGLE',
    'quadTours.double': 'DOBLE',
    'quadTours.perQuad': 'POR QUAD',
    'quadTours.kidsTravel': 'NIÑOS VIAJAN GRATIS!',
    'quadTours.ageRange': '7 - 16 AÑOS',
    'quadTours.adventureForAll': '¡AVENTURA PARA TODOS!',
    
    // Map
    'map.doubleClickToActivate': '2 toques para activar',
    
    // Cookie Consent
    'cookies.title': 'Gestionar el consentimiento de cookies',
    'cookies.description': 'Para ofrecerle la mejor experiencia, utilizamos tecnologías como las cookies para almacenar información en su dispositivo o acceder a ella. El consentimiento a estas tecnologías nos permitirá procesar datos como el comportamiento de navegación o identificadores únicos en este sitio. La falta de consentimiento o la retirada del mismo puede afectar negativamente a determinadas características y funciones.',
    'cookies.accept': 'Aceptar',
    'cookies.deny': 'Denegar',
    'cookies.preferences': 'Ver Preferencias',
    'cookies.cookiePolicy': 'Política de Cookies',
    'cookies.privacyPolicy': 'Política de Privacidad',
    'cookies.legalNotice': 'Aviso legal',
    'cookies.shortDescription': 'Utilizamos cookies para mejorar su experiencia',
  },
  en: {
    // Header
    'header.rental': 'Rental',
    'header.tours': 'Guided Tours',
    'header.shop': 'Shop',
    'header.contact': 'Contact',
    'header.scanPrices': 'Rent a Quad',
    
    // Hero Section
    'hero.title': 'Explore with Freedom',
    'hero.subtitle': 'Rent bikes, electric scooters, motorcycles, cars and join our guided tours. Adventure awaits you at every corner.',
    'hero.viewRentals': 'View Rentals',
    'hero.bookTour': 'Book Tour',
    
    // Services Section
    'services.title': 'Our Services',
    'services.subtitle': 'Discover all the options we have to make your experience unforgettable',
    'services.bikeRental': 'Bike Rental',
    'services.bikeDescription': 'Electric bikes, mountain bikes, city bikes and more',
    'services.guidedTours': 'Guided Tours',
    'services.toursDescription': 'Tours and excursions to the best places',
    'services.carRental': 'Car Rental',
    'services.carDescription': 'From compact cars to 9-seater minibuses',
    'services.motosScooters': 'Motorcycles & Scooters',
    'services.motosDescription': 'Motorcycles, electric scooters and quads',
    'services.repairService': 'Repair Service',
    'services.repairDescription': 'Repair and maintenance',
    'services.store': 'Shop',
    'services.storeDescription': 'Discover our selection of products and accessories',
    // Common
    'common.seeMore': 'See more →',
    
    // Location Section
    'location.title': 'Where We Are',
    'location.description.before': 'Visit us at our privileged location on the shores of the Alboran Sea in La Colina ',
    'location.description.after': ' where you can find everything you need for your adventure.',
    'location.subtitle': 'We are located in the heart of Torremolinos, ready for your next adventure',
    'location.description': 'Visit us at our privileged location on the shores of the Mediterranean Sea in Torremolinos where you can find everything you need for your adventure.',
    'location.ourLocation': 'Our Location',
    'location.address': 'Calle de la Playa, 22',
    'location.city': '29620 Torremolinos, Málaga, La Colina',
    'location.country': 'Spain',
    'location.phone': '+34 655 707 412',
    'location.email': 'rentairstreet@gmail.com',
    'location.hours': 'Monday to Sunday: 9:00 - 22:00',
    'location.streetView': 'View on Street View',
    
    // Second Store Section
    'secondStore.title': 'You can return the bike at our',
    'secondStore.otherStore': 'other store',
    'secondStore.available': 'available',
    'secondStore.secondLocation': 'Second location',
    'secondStore.address': 'Calle Obispo Juan Alonso 8',
    'secondStore.city': 'Los Álamos, Torremolinos',
    'secondStore.description': 'For your convenience, you can also return your bike at our second store. Perfect for routes that end in that area of Torremolinos.',
    'secondStore.viewOnMaps': 'View on Google Maps',
    
    // Prices Section
    'prices.title': 'Featured Prices',
    'prices.subtitle': 'Some of our most popular offers',
    'prices.cityBike': 'City Bike',
    'prices.cityBikeDesc': 'Perfect for urban rides',
    'prices.electricBike': 'Electric Bike',
    'prices.electricBikeDesc': 'No effort, maximum fun',
    'prices.traditionalScooter': 'Traditional Scooter',
    'prices.traditionalScooterDesc': 'Light and fun for short distances',
    'prices.hour': '1 hour',
    'prices.allDay': 'All day (11h)',
    'prices.halfHour': '30 min',
    
    // Featured Tours
    'tours.title': 'Featured Tours',
    'tours.subtitle': 'Discover our most popular experiences and live unforgettable adventures',
    'tours.dolphinTrip': 'Dolphin Trip',
    'tours.dolphinDesc': 'Dolphin watching in their natural habitat. Perfect for families.',
    'tours.granadaAlhambra': 'Granada Alhambra',
    'tours.granadaDesc': 'Visit the majestic Alhambra and the Generalife gardens.',
    'tours.horseRiding': 'Horse Riding',
    'tours.horseDesc': 'Enjoy a relaxing horse ride through unique natural landscapes.',
    'tours.adults': 'Adults',
    'tours.children': 'Children',
    'tours.familyExperience': 'Family experience',
    'tours.thursdayFriday': 'Thursday and Friday',
    'tours.unescoHeritage': 'UNESCO Heritage',
    'tours.officialGuide': 'Official guide included',
    'tours.duration': '1.30 hours',
    'tours.onePersonPerHorse': '1 person per horse',
    'tours.expertGuide': 'Expert guide included',
    'tours.viewAllTours': 'View All Tours',
    // Tours Info Sections (EN)
    'tours.specialPrices.title': 'Special Prices',
    'tours.specialPrices.childrenFree': 'Children (0-3 years): FREE!',
    'tours.specialPrices.childrenDiscount': 'Children (4-11 years): 25% discount',
    'tours.specialPrices.familyGroups': 'Family groups: Ask for special discounts',
    'tours.specialPrices.earlyBooking': 'Early booking: Best prices guaranteed',
    'tours.languages.title': 'Available Languages',
    'tours.languages.spanish': 'Spanish',
    'tours.languages.english': 'English',
    'tours.languages.french': 'French',
    'tours.languages.german': 'German',
    'tours.languages.italian': 'Italian',
    'tours.importantInfo.title': 'Important Information',
    'tours.importantInfo.includesTitle': 'What’s included?',
    'tours.importantInfo.includes.transport': 'Transport by air-conditioned coach',
    'tours.importantInfo.includes.guide': 'Official certified guide',
    'tours.importantInfo.includes.insurance': 'Travel insurance',
    'tours.importantInfo.includes.tickets': 'Entrance tickets (depending on tour)',
    'tours.importantInfo.includes.assistance': 'Assistance throughout the tour',
    'tours.importantInfo.recommendationsTitle': 'Recommendations',
    'tours.importantInfo.recommendations.shoes': 'Comfortable walking shoes',
    'tours.importantInfo.recommendations.sun': 'Sunscreen and cap',
    'tours.importantInfo.recommendations.camera': 'Camera',
    'tours.importantInfo.recommendations.docs': 'Personal documentation',
    'tours.importantInfo.recommendations.booking': 'Book 48h in advance',
    
    // Contact Section
    'contact.title': 'Contact',
    
    // Footer
    'footer.rights': '© 2025 Free Air Street. All rights reserved.',
    
    // Rental Page
    'rental.title': 'Vehicle Rental',
    'rental.subtitle': 'Discover the freedom to move around Torremolinos with our bikes, cars, motorcycles, electric scooters and quads. Choose your ideal vehicle and live a unique experience!',
    'rental.bicycles': 'Bicycles',
    'rental.cars': 'Cars',
    'rental.motorcycles': 'Motorcycles',
    'rental.quads': 'Quads',
    'rental.scooters': 'Scooters',
    'rental.accessories': 'Accessories',
    'rental.selectPrice': 'Select Price',
    'rental.reserve': 'Reserve',
    'rental.allDay': 'All day (11h)',
    'rental.day': 'Day',
    'rental.days': 'days',
    'rental.hour': 'hour',
    'rental.hours': 'hours',
    'rental.min': 'min',
    'rental.consultPrice': 'Consult price',
    'rental.consultAvailability': 'Check availability',
    'rental.features': 'Features:',
    'rental.prices': 'Prices:',
    'rental.for': 'for',
    'rental.model': 'Model:',
    'rental.autonomy': 'Autonomy',
    'rental.speed': 'Speed',
    'rental.carRequirements.title': 'Car rental requirements:',
    'rental.carRequirements.license': 'Valid driving license',
    'rental.carRequirements.passport': 'Passport or ID',
    'rental.carRequirements.creditCard': 'Credit card for deposit',
    'rental.carRequirements.age': 'Minimum age: 21 years',
    'rental.carRequirements.models': 'Models may vary according to availability',
    // Motorcycle Requirements
    'rental.motorcycleRequirements.title': 'Motorcycle Rental Requirements',
    'rental.motorcycleRequirements.license': 'Valid driving license (A1, A2 or A depending on displacement)',
    'rental.motorcycleRequirements.reservation': 'Reservation required in advance',
    'rental.motorcycleRequirements.id': 'Identity document (ID or passport)',
    'rental.motorcycleRequirements.minAge': 'Minimum age: 16 (50cc), 18 (125cc), 20 (+300cc)',
    'rental.motorcycleRequirements.deposit': 'Security deposit required',
    'rental.motorcycleRequirements.helmet': 'Approved helmet included',
    // Quad Requirements
    'rental.quadRequirements.title': 'Quad Rental Requirements',
    'rental.quadRequirements.license': 'Valid driving license (B or higher)',
    'rental.quadRequirements.reservation': 'Reservation required in advance',
    'rental.quadRequirements.id': 'Identity document (ID or passport)',
    'rental.quadRequirements.minAge': 'Minimum age: 18 years',
    'rental.quadRequirements.deposit': 'Security deposit required',
    'rental.quadRequirements.helmet': 'Approved helmet included',
    'rental.quadRequirements.safetyBriefing': 'Mandatory safety briefing',
    // Vehicle translations
    'rental.vehicles.cityBike.name': 'City Bike',
    'rental.vehicles.cityBike.description': 'Perfect for urban rides and city commuting',
    'rental.vehicles.cityBike.allDay': 'All day',
    'rental.vehicles.cityBike.features': ['Front basket', 'LED lights', '7-speed gear', 'Comfortable seat'],
    'rental.vehicles.mountainBike.name': 'MOUNTAIN BIKE / ROAD BIKE',
    'rental.vehicles.mountainBike.description': 'Ideal for mountain and road adventures',
    'rental.vehicles.mountainBike.allDay': 'All day (11h)',
    'rental.vehicles.mountainBike.features': ['Front suspension', 'Disc brakes', '21 speeds', 'All-terrain tires'],
    'rental.vehicles.electricBike.name': 'ELECTRIC BIKE',
    'rental.vehicles.electricBike.description': 'Pedal assist for effortless rides',
    'rental.vehicles.electricBike.allDay': 'All day (11h)',
    'rental.vehicles.electricBike.features': ['Electric motor', 'Long-lasting battery', 'LCD display', 'Charger included'],
    'rental.vehicles.fatBike.name': 'FAT BIKE ELECTRIC',
    'rental.vehicles.fatBike.description': 'Electric bike with wide tires for any terrain',
    'rental.vehicles.fatBike.allDay': 'All day (11h)',
    'rental.vehicles.fatBike.features': ['Wide tires', 'Powerful motor', 'Full suspension', 'Water resistant'],
    'rental.vehicles.toyotaAygo.group': 'Group A',
    'rental.vehicles.toyotaAygo.description': 'Compact and economical, perfect for the city',
    'rental.vehicles.toyotaAygo.duration1': '1 Day',
    'rental.vehicles.toyotaAygo.features': ['Air conditioning', 'Power steering', '5 doors', 'Efficient consumption'],
    
    // Tours Page
    'tours.pageTitle': 'Guided Tours and Excursions',
    'tours.pageSubtitle': 'Discover the most incredible places in Andalusia with our organized excursions and unique activities',
    'tours.excursions': 'Excursions',
    'tours.activities': 'Activities',
    'tours.boatActivities': 'Boat Activities',
    'tours.availableDays': 'Available days:',
    'tours.price': 'Price',
    'tours.from': 'From',
    'tours.adult': 'Adult',
    'tours.child': 'Child',
    'tours.person': 'person',
    'tours.capacity': 'Capacity',
    'tours.location': 'Location',
    'tours.highlights': 'Highlights',
    'tours.languages': 'Available languages',
    'tours.spanish': 'Spanish',
    'tours.english': 'English',
    'tours.french': 'French',
    'tours.german': 'German',
    'tours.italian': 'Italian',
    'tours.importantInfo': 'Important Information',
    'tours.whatIncludes': 'Includes:',
    'tours.recommendations': 'Recommendations',
    'tours.consult': 'Consult',
    'tours.consultAvailability': 'Check availability',
    'tours.reserveActivity': 'Reserve Activity',
    'tours.reserveRide': 'Reserve ride',
    'tours.includes1': 'Air-conditioned bus transport',
    'tours.includes2': 'Official guide in Spanish',
    'tours.includes3': 'Travel insurance included',
    'tours.includes4': 'Free time to explore',
    'tours.rec1': 'Wear comfortable shoes',
    'tours.rec2': 'Sun protection recommended',
    'tours.rec3': 'Camera to capture moments',
    'tours.rec4': 'Documentation in order',
    
    // Contact Page
    'contact.subtitle': 'Do you have any questions or need more information? We are here to help you. Contact us and we will respond as soon as possible.',
    'contact.phone': 'Phone',
    'contact.phoneHours': 'Available from 9:00 to 22:00',
    'contact.email': 'Email',
    'contact.emailResponse': '24h response',
    'contact.location': 'Location',
    'contact.hours': 'Hours',
    'contact.schedule': 'Mon - Sun: 9:00 - 22:00',
    'contact.openDaily': 'Open every day',
    'contact.mondayToSunday': 'Monday - Sunday',
    'contact.regularHours': '9:00 - 22:00',
    'contact.holidays': 'Holidays',
    'contact.holidayHours': '10:00 - 19:00',
    'contact.form.title': 'Send us a message',
    'contact.form.description': 'Fill out the form and we will get in touch with you as soon as possible.',
    'contact.form.name': 'Name',
    'contact.form.namePlaceholder': 'Your full name',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.phone': 'Phone',
    'contact.form.phonePlaceholder': '+34 XXX XXX XXX',
    'contact.form.subject': 'Subject',
    'contact.form.subjectPlaceholder': 'How can we help you?',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Tell us more details about your inquiry...',
    'contact.form.send': 'Send message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent!',
    'contact.form.successMessage': 'We will respond as soon as possible.',
    'contact.form.sendAnother': 'Send another message',
    'contact.form.error': 'Error sending message',
    'contact.form.errorMessage': 'Please try again or contact us directly.',
    'contact.info.title': 'Contact Information',
    'contact.info.phone': 'Phone',
    'contact.info.phoneDesc': 'Call us from 9:00 to 22:00',
    'contact.info.email': 'Email',
    'contact.info.emailDesc': '24h response',
    'contact.info.location': 'Location',
    'contact.info.address': 'Calle de la Playa, 22',
    'contact.info.city': '29620 - Torremolinos',
    'contact.hours.title': 'Business Hours',
    'contact.hours.weekdays': 'Monday - Sunday',
    'contact.hours.weekdaysTime': '9:00 - 22:00',
    'contact.hours.holidays': 'Holidays',
    'contact.hours.holidaysTime': '10:00 - 19:00',
    'contact.map.title': 'Our Location',
    'contact.callNow': 'Call Now',
    
    // Quad Tours
    'quadTours.title': 'UNFORGETTABLE EXPERIENCE',
    'quadTours.subtitle': 'WE HAVE 3 QUAD TOURS AVAILABLE:',
    'quadTours.hour': 'HOUR',
    'quadTours.tour': 'TOUR',
    'quadTours.price': 'PRICE',
    'quadTours.single': 'SINGLE',
    'quadTours.double': 'DOUBLE',
    'quadTours.perQuad': 'PER QUAD',
    'quadTours.kidsTravel': 'KIDS TRAVEL FREE!',
    'quadTours.ageRange': '7 - 16 YEARS OLD',
    'quadTours.adventureForAll': 'ADVENTURE FOR ALL!',
    
    // Map
    'map.doubleClickToActivate': '2 taps to activate',
    
    // Cookie Consent
    'cookies.title': 'Manage cookie consent',
    'cookies.description': 'To provide you with the best experience, we use technologies such as cookies to store information on your device or access it. Consent to these technologies will allow us to process data such as browsing behavior or unique identifiers on this site. Lack of consent or withdrawal of consent may negatively affect certain features and functions.',
    'cookies.accept': 'Accept',
    'cookies.deny': 'Deny',
    'cookies.preferences': 'View Preferences',
    'cookies.cookiePolicy': 'Cookie Policy',
    'cookies.privacyPolicy': 'Privacy Policy',
    'cookies.legalNotice': 'Legal Notice',
    'cookies.shortDescription': 'We use cookies to improve your experience',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es')

  const t = (key: string): string | string[] => {
    const dict = (translations as any)[language] as Record<string, string | string[]>
    return dict[key] ?? key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}